### PR TITLE
Fixed spelling mistake

### PR DESCRIPTION
**Pull request by DebitCardz**

### CODE REVIEW

**Comment by smartfrigde** [comment]
Open source power 😁😆🦾🦾🦾🦾

**Comment by lexisother** [comment]
This isn't a spelling mistake? It's supposed to say "pat", as it stands for "personal access token".

**Comment by CanadaHonk** [comment]
It is GitHub PAT (Personal Access Token), not path.

**Comment by DebitCardz** [comment]
> It is GitHub PAT (Personal Access Token), not path.

Ah, I just looked at the field below it and noticed they were different, my bad.

**Pull request closed without merging**
